using UnityEditor.ShaderGraph.Internal;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerController : MonoBehaviour
{
    // reference to action map that holds all the player actions
    public InputActionAsset inputActions;
    // Specific Actions below
     InputAction p_Move;
    //public InputAction p_Look;
    //InputAction p_Attack;
    public InputAction p_Interact;

    [SerializeField]
    Rigidbody2D playerRig;

    Vector2 p_MoveChange;
   // Vector2 p_LookChange;
    float walkSpeed;
    //float rotationSpeed;


    void Awake()
    {
        walkSpeed = 5f;
        p_Move = InputSystem.actions.FindAction("Move");
        //p_Look = InputSystem.actions.FindAction("Look");
        //p_Attack = InputSystem.actions.FindAction("Attack");
        p_Interact = InputSystem.actions.FindAction("Interact");
        playerRig = GetComponent<Rigidbody2D>();

        // get rigid body component
    }

    void Update()
    {
        p_MoveChange = p_Move.ReadValue<Vector2>();
        //p_LookChange = p_Look.ReadValue<Vector2>();
    }

    void FixedUpdate()
    {
        PlayerWalk();
    }

    // Enables Player contol scheme from Input Action asset generated by default
    private void OnEnable()
    {
        inputActions.FindActionMap("PLayer").Enable();
    }
    // Disables Player contol scheme from Input Action asset generated by default
    private void OnDisable()
    {
        inputActions.FindActionMap("PLayer").Disable();
    }
    //Fuction called in FixedUpdate to link player components like animation and transform to a speed parameter like a float number
    void PlayerWalk()
    {
        // animation component would be inserted here to update animation by movement change on the Y axis. change reference is p_MoveChange if in 3d

        //do transform to move player here via rigidbody
        // Form 1 are non-Omni_Movement formula
        // forumla 1 rigidbody Move Positoin Func = (character current rig postion + general z-forward vector * movement change * player walk speed * Time.deltaTime)
        //This formula below is best for 2d
        // formual 3 rigidybody Move Position Func = (character current rig postion + vector2.one (1,1) * movementChange * player walk speed * Time.deltaTimne)
        playerRig.MovePosition(playerRig.position + Vector2.one * p_MoveChange * walkSpeed * Time.deltaTime); 

        
    }
    
}



